"""Base de conhecimento por setor para o sistema RAG."""

KNOWLEDGE_BASE = {
    "financeiro": [
        "Boletos podem ser prorrogados por até 30 dias sem multa mediante solicitação formal.",
        "Prorrogações acima de 30 dias têm acréscimo de 2% ao mês sobre o valor em aberto.",
        "Negociações de débitos em atraso devem ser formalizadas por e-mail ao setor financeiro.",
        "Desconto para pagamento antecipado: até 5% sobre o valor do boleto quando pago com 10 dias de antecedência.",
        "Emissão de segunda via de boleto: prazo de até 24 horas úteis após solicitação.",
        "Nota fiscal emitida incorretamente requer cancelamento em até 5 dias corridos após emissão.",
        "Parcelamento disponível em até 12x para valores acima de R$ 5.000, sujeito à aprovação.",
        "Condições de pagamento padrão: 30, 60 ou 90 dias conforme contrato.",
        "Clientes com mais de 90 dias de atraso são encaminhados ao setor jurídico para cobrança formal.",
        "Multa por atraso: 2% ao mês + juros de 1% ao mês sobre o valor em aberto.",
        "Solicitação de crédito ou limite de crédito: prazo de análise de 3 a 5 dias úteis.",
        "Baixa de pagamento: confirmada em até 2 dias úteis após comprovante enviado.",
    ],
    "logistica": [
        "Prazo padrão de entrega: 5 a 7 dias úteis a partir da confirmação do pedido.",
        "Entrega expressa disponível com prazo de 2 a 3 dias úteis, com custo adicional de 30%.",
        "Rastreamento disponível 24 horas após o despacho da mercadoria via código fornecido por e-mail.",
        "Atrasos superiores a 3 dias devem ser comunicados proativamente ao cliente em até 24 horas.",
        "Em caso de atraso superior a 10 dias úteis, o cliente tem direito a compensação de 5% sobre o valor do pedido.",
        "Avaria ou extravio de mercadoria: abrir chamado em até 48 horas após entrega para cobertura de seguro.",
        "Entregas parciais são informadas com 24 horas de antecedência e protocolo registrado.",
        "Horário de entrega: segunda a sexta-feira, das 8h às 18h. Sábados mediante acordo prévio.",
        "Devolução de mercadoria: prazo de 7 dias corridos após o recebimento, mercadoria sem uso.",
        "Agendamento de entrega especial: disponível para pedidos acima de R$ 10.000.",
        "Seguro de carga incluso nos fretes acima de R$ 5.000, coberto contra roubo e avaria.",
    ],
    "comercial": [
        "Contato com representante comercial: segunda a sexta-feira, das 8h às 18h.",
        "Contratos têm prazo mínimo de 12 meses com renovação automática.",
        "Aviso de cancelamento ou não renovação: 30 dias antes do vencimento, por escrito.",
        "Descontos acima de 10% requerem aprovação formal do gerente comercial, prazo de 2 dias úteis.",
        "Proposta comercial enviada em até 2 dias úteis após solicitação documentada.",
        "Divergências em pedidos devem ser relatadas em até 48 horas após o recebimento da mercadoria.",
        "Alteração de pedido confirmado: possível apenas em até 24 horas após a confirmação do pedido.",
        "Visita do representante comercial: disponível mediante agendamento com 48 horas de antecedência.",
        "Programa de fidelidade: clientes com contrato acima de 24 meses têm desconto progressivo de até 8%.",
        "Upgrade de plano ou produto: comercial analisa necessidades e envia proposta em até 3 dias úteis.",
        "Tabela de preços atualizada trimestralmente, com 30 dias de aviso antes de reajustes.",
    ],
    "juridico": [
        "Distrato de contrato requer notificação prévia formal de 30 dias corridos.",
        "Rescisão antecipada pode gerar multa contratual de 20% sobre o valor remanescente do contrato.",
        "Análise jurídica de documentos e contratos: prazo de 5 a 10 dias úteis após protocolo aberto.",
        "Disputas contratuais são encaminhadas ao setor jurídico para análise e mediação.",
        "Documentação necessária para distrato: contrato original, notificação formal, CNPJ ativo.",
        "Foro de resolução de conflitos: conforme cláusula de eleição de foro prevista em contrato.",
        "Acordo extrajudicial: possível mediante análise do jurídico, prazo de 10 dias para resposta.",
        "Casos de inadimplência acima de 90 dias são automaticamente encaminhados para cobrança jurídica.",
        "Certidão negativa de débitos: emitida em até 5 dias úteis após quitação total.",
    ],
    "geral": [
        "Atendimento disponível de segunda a sexta-feira, das 8h às 18h.",
        "Todos os atendimentos geram protocolos automáticos para rastreabilidade e histórico.",
        "Prazo de resposta padrão do suporte: até 24 horas úteis.",
        "Canal de atendimento prioritário (SLA de 4h) disponível para clientes de segmento Enterprise.",
        "Para agilizar o atendimento, tenha em mãos o CNPJ e o número do contrato.",
        "Pesquisa de satisfação enviada por e-mail após encerramento de cada protocolo.",
    ],
}
